services:
  django:
    image: registry.cn-hangzhou.aliyuncs.com/x014/music_tag_web:latest
    container_name: music-tag-web
    expose:
      - "8001"
    volumes:
      - E:/music/mp3:/app/media:z # 配置本地音乐文件夹
    restart: always
    environment:
      dockerrun: "yes"
    depends_on:
      - redis
      - db
    networks:
      - internal
    command: /start
  celeryworker:
    image: registry.cn-hangzhou.aliyuncs.com/x014/music_tag_web:latest
    container_name: music_celeryworker
    environment:
      dockerrun: "yes"
    ports: [ ]
    volumes:
      - E:/music/mp3:/app/media:z # 配置本地音乐文件夹
    networks:
      - internal
    depends_on:
      - redis
      - db
    command: /start-celeryworker
  celerybeat:
    image: registry.cn-hangzhou.aliyuncs.com/x014/music_tag_web:latest
    container_name: music_celerybeat
    environment:
      dockerrun: "yes"
    ports: [ ]
    networks:
      - internal
    depends_on:
      - redis
      - db
    command: /start-celerybeat
  redis:
    image: redis:7.2-alpine
    restart: always
    container_name: music_redis
    networks:
      - internal
    expose:
      - "6379"
  db:
    image: registry.cn-hangzhou.aliyuncs.com/x014/mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: music3
      MYSQL_USER: music_user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - internal
    expose:
      - "3306"
  nginx:
    image: nginx:1.25-alpine
    restart: always
    container_name: music_nginx
    ports:
      - "9150:80"
    networks:
      - internal
    depends_on:
      - django
    volumes:
      - ./compose/prod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - E:/music/mp3:/app/media:z # 配置本地音乐文件夹
networks:
  internal: